title: Nqobile Zulu
#logo: /displaypic.jpg
description: I am a Junior Analytics Engineer with a passion for turning data into meaningful insights. 
I have experience in data modeling, warehousing, and visualization, working with tools like Fivetran, Snowflake, dbt, and Looker. At Valenture Institute,
I played a key role in transforming data for business decisions, creating dashboards, and even contributing to forecasting and predictive modelling.
Beyond the technical side, I enjoy problem-solving and collaborating with different teams to understand their data needs and deliver impactful solutions. 
I thrive in environments that encourage learning and innovation, and I’m always looking for ways to improve processes and drive efficiency.
I am excited to bring my skills and curiosity to a team that values data-driven decision-making.
show_downloads: true
theme: jekyll-theme-minimal
